In [1]:
import pandas as pd

In [14]:
df = pd.read_csv(r"C:\Users\LENOVO\Downloads\ASE-ETL-dataset_1_1 (1)\employee_202510161125.csv",sep="|")

In [2]:
csv_files = [
    r"C:\Users\LENOVO\Downloads\ASE-ETL-dataset_1_1 (1)\timesheet_202510161124.csv",
    r"c:\Users\LENOVO\Downloads\ASE-ETL-dataset_1_1 (1)\timesheet_202510161122.csv",
    r"C:\Users\LENOVO\Downloads\ASE-ETL-dataset_1_1 (1)\timesheet_202510161121.csv",
    r"C:\Users\LENOVO\Downloads\ASE-ETL-dataset_1_1 (1)\timesheet_202509151540.csv"
]

df2 = pd.concat(
    (pd.read_csv(file, sep="|") for file in csv_files),
    ignore_index=True
)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14520\2043961082.py:9: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  (pd.read_csv(file, sep="|") for file in csv_files),

In [33]:
df.shape

(50, 34)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 34 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   client_employee_id     50 non-null     int64
 1   first_name             50 non-null     object
 2   middle_name            0 non-null      float64
 3   last_name              50 non-null     object
 4   preferred_name         50 non-null     object
 5   job_code               50 non-null     int64
 6   job_title              50 non-null     object
 7   job_start_date         50 non-null     object
 8   organization_id        50 non-null     object
 9   organization_name      50 non-null     object
 10  department_id          50 non-null     object
 11  department_name        50 non-null     object
 12  dob                    50 non-null     object
 13  hire_date              50 non-null     object
 14  recent_hire_date       50 non-null     object
 15  anniversary_date       50 non-null     object
 16  term_date              6 non-null      object
 17  years_of_experience    0 non-null      float64
 18  work_email             50 non-null     object
 19  address                50 non-null     object
 20  city                   50 non-null     object
 21  state                  50 non-null     object
 22  zip                    0 non-null      float64
 23  country                50 non-null     object
 24  manager_employee_id    50 non-null     int64
 25  manager_employee_name  0 non-null      float64
 26  fte_status             50 non-null     object
 27  is_per_deim            0 non-null      float64
 28  cell_phone             50 non-null     object
 29  work_phone             0 non-null      float64
 30  scheduled_weekly_hour  50 non-null     int64
 31  active_status          50 non-null     int64
 32  termination_reason     6 non-null      object
 33  clinical_level         0 non-null      float64
dtypes: float64(7), int64(5), object(22)
memory usage: 13.4+ KB

In [19]:
df[['zip',"country","state","city"]].isna().sum()

zip        50
country     0
state       0
city        0
dtype: int64

In [9]:
df.isna().sum()

client_employee_id        0
first_name                0
middle_name              50
last_name                 0
preferred_name            0
job_code                  0
job_title                 0
job_start_date            0
organization_id           0
organization_name         0
department_id             0
department_name           0
dob                       0
hire_date                 0
recent_hire_date          0
anniversary_date          0
term_date                44
years_of_experience      50
work_email                0
address                   0
city                      0
state                     0
zip                      50
country                   0
manager_employee_id       0
manager_employee_name    50
fte_status                0
is_per_deim              50
cell_phone                0
work_phone               50
scheduled_weekly_hour     0
active_status             0
termination_reason       44
clinical_level           50
dtype: int64

In [3]:
df2.shape

(412571, 14)

In [9]:
df2["home_department_name"].sample(5)

180923           Nursing Mother/Infant
247037    HHMA-Gastrointestinal Clinic
175994               Bone Marrow Coord
90122                              NaN
202917            Outside Clinic Clyne
Name: home_department_name, dtype: object

In [28]:
df2.columns

Index(['client_employee_id', 'department_id', 'department_name',
       'home_department_id', 'home_department_name', 'pay_code',
       'punch_in_comment', 'punch_out_comment', 'hours_worked',
       'punch_apply_date', 'punch_in_datetime', 'punch_out_datetime',
       'scheduled_start_datetime', 'scheduled_end_datetime'],
      dtype='object')

In [47]:
df2.isna().sum()

client_employee_id               0
department_id               157183
department_name             156412
home_department_id          149978
home_department_name        149978
pay_code                         0
punch_in_comment                 0
punch_out_comment                0
hours_worked                     0
punch_apply_date                 0
punch_in_datetime                0
punch_out_datetime               0
scheduled_start_datetime    232455
scheduled_end_datetime      232455
dtype: int64

In [11]:
home_to_work = (
    df2.groupby('home_department_id')['department_id']
    .nunique()
    .reset_index(name='unique_work_departments')
    .sort_values(by='unique_work_departments', ascending=False)
)

print(home_to_work.head(20))

    home_department_id  unique_work_departments
173          201-10046                       24
174          201-10047                       23
178          201-10051                       19
325          201-12493                       17
155          201-10011                       16
151          201-10005                       16
255          201-10188                       16
356          201-13918                       16
153          201-10007                       15
324          201-12485                       15
9           1100-10051                       15
334          201-12779                       14
166          201-10038                       13
234          201-10141                       13
154          201-10009                       11
357          201-14059                       11
62          1100-13610                       11
160          201-10018                       10
63          1100-13611                       10
152          201-10006                       10

In [13]:
employee_movement = (
    df2.groupby('client_employee_id')['department_id']
    .nunique()
    .reset_index(name='departments_worked')
    .sort_values(by='departments_worked', ascending=False)
)

print(employee_movement.head(20))

      client_employee_id  departments_worked
14115             506218                  17
11332             416728                  16
14053             505997                  16
14081             506145                  14
12069             421210                  14
12838             502213                  13
10833             412722                  13
4072              403144                  13
11124             415122                  13
13444             504352                  13
13806             505435                  12
11820             419816                  12
14361             506662                  12
12808             502109                  12
10977             413992                  12
14867             507902                  12
14391             506717                  11
13751             505308                  11
13410             504217                  11
11826             419890                  11

In [15]:
employee_ids = set(df['client_employee_id'])
invalid_managers = df[
    df['manager_employee_id'].notna() &
    ~df['manager_employee_id'].isin(employee_ids)
]

print(invalid_managers)

    client_employee_id  first_name  middle_name last_name preferred_name  \
0                   37   Demo00037          NaN     Nurse      Demo00037
1               507210  Demo507210          NaN     Nurse     Demo507210
2                   80   Demo00080          NaN     Nurse      Demo00080
3               503912  Demo503912          NaN     Nurse     Demo503912
5               506323  Demo506323          NaN     Nurse     Demo506323
6                   68   Demo00068          NaN     Nurse      Demo00068
8                  131   Demo00131          NaN     Nurse      Demo00131
9                  214   Demo00214          NaN     Nurse      Demo00214
10              505453  Demo505453          NaN     Nurse     Demo505453
12                 138   Demo00138          NaN     Nurse      Demo00138
13              507273  Demo507273          NaN     Nurse     Demo507273
15              507238  Demo507238          NaN     Nurse     Demo507238
16              507473  Demo507473          NaN     Nurse     Demo507473
17              506357  Demo506357          NaN     Nurse     Demo506357
18              507272  Demo507272          NaN     Nurse     Demo507272
19              506444  Demo506444          NaN     Nurse     Demo506444
21              506342  Demo506342          NaN     Nurse     Demo506342
24              505559  Demo505559          NaN     Nurse     Demo505559
26              507472  Demo507472          NaN     Nurse     Demo507472
28              506359  Demo506359          NaN     Nurse     Demo506359
30                 267   Demo00267          NaN     Nurse      Demo00267
35              506423  Demo506423          NaN     Nurse     Demo506423
36              506390  Demo506390          NaN     Nurse     Demo506390
37              507474  Demo507474          NaN     Nurse     Demo507474
38              507226  Demo507226          NaN     Nurse     Demo507226
39              505444  Demo505444          NaN     Nurse     Demo505444
40              505345  Demo505345          NaN     Nurse     Demo505345
41                 747   Demo00747          NaN     Nurse      Demo00747
42              505347  Demo505347          NaN     Nurse     Demo505347
43                 772   Demo00772          NaN     Nurse      Demo00772
44              506333  Demo506333          NaN     Nurse     Demo506333
45                 367   Demo00367          NaN     Nurse      Demo00367
46                 493   Demo00493          NaN     Nurse      Demo00493
47                 449   Demo00449          NaN     Nurse      Demo00449
48                 618   Demo00618          NaN     Nurse      Demo00618
49                 518   Demo00518          NaN     Nurse      Demo00518

    job_code                                     job_title job_start_date  \
0       1995                              Manager, CT Scan     1998-06-01
1       1001                   Administrative Assistant II     1994-01-11
2       4377              Ultrasound Technologist III - PD     1998-07-16
3       2129                               Nurse Assistant     1994-04-04
5       1478                       Clinical Coordinator-RN     1999-08-02
6       1195                           Unit Coordinator II     1998-07-07
8       1001                   Administrative Assistant II     1998-08-26
9       1090                  Patient Access Coordinator I     1998-10-05
10      2324                  Clinical Manager-Home Health     1990-11-12
12      3599                 Clinical Director-Informatics     1998-08-24
13      1437                 Physical Therapy Assistant II     1995-08-28
15      4238                      Manager, Nursing Support     2011-07-08
16      4688           Senior Clinical Staff Educator - PD     1990-10-01
17      4445             Physical Therapist - Care at Home     2017-05-15
18      1437                 Physical Therapy Assistant II     1993-11-15
19      4944              Patient Service Representative I     1998-08-03
21      4442         Occupational Therapist - Care at Home     2009-03-09
24      3592                            RN IV Complex Care     1998-09-14
26      1693                    Scheduling Coordinator III     2000-09-25
28      4445             Physical Therapist - Care at Home     2009-10-04
30      3588                                         RN IV     1998-11-16
35      1100  Health Information Management Coordinator II     1999-09-27
36      3978                           Benefits Consultant     1999-07-26
37      2103                       Care Transition Liaison     2018-03-05
38      2201                                     RN-Intake     1995-04-03
39      1001                   Administrative Assistant II     1999-09-08
40      2133                   RN-Home Health-Case Manager     1999-12-06
41      4802                              LPN - Outpatient     2021-09-27
42      2133                   RN-Home Health-Case Manager     1993-06-07
43      5002                    RN - Surgical First Assist     1999-11-01
44      4674                        Epic Reporting Analyst     1993-08-21
45      2421                     Supervisor, Sleep Therapy     1999-01-27
46      3588                                         RN IV     1999-05-10
47      2819             RN I, Clinical Nurse - Ambulatory     2022-10-03
48      3588                                         RN IV     1999-08-02
49      2468                      Respiratory Therapist II     1999-05-24

            organization_id        organization_name  ... manager_employee_id  \
0   Lowell General Hospital  Lowell General Hospital  ...                9569
1              Care at Home             Care at Home  ...              507237
2   Lowell General Hospital  Lowell General Hospital  ...                5119
3   Lowell General Hospital  Lowell General Hospital  ...                3297
5              Care at Home             Care at Home  ...              502646
6   Lowell General Hospital  Lowell General Hospital  ...               92189
8   Lowell General Hospital  Lowell General Hospital  ...                9181
9   Lowell General Hospital  Lowell General Hospital  ...                4380
10             Care at Home             Care at Home  ...              507537
12  Lowell General Hospital  Lowell General Hospital  ...              303007
13             Care at Home             Care at Home  ...              502646
15             Care at Home             Care at Home  ...              500713
16             Care at Home             Care at Home  ...              507486
17             Care at Home             Care at Home  ...              502646
18             Care at Home             Care at Home  ...              502646
19           Tufts Medicine           Tufts Medicine  ...              412620
21             Care at Home             Care at Home  ...              502646
24  Lowell General Hospital  Lowell General Hospital  ...                5892
26             Care at Home             Care at Home  ...              507237
28             Care at Home             Care at Home  ...              502646
30  Lowell General Hospital  Lowell General Hospital  ...               13706
35           Tufts Medicine           Tufts Medicine  ...               29686
36           Tufts Medicine           Tufts Medicine  ...              507792
37             Care at Home             Care at Home  ...              510271
38             Care at Home             Care at Home  ...              507516
39             Care at Home             Care at Home  ...              507237
40             Care at Home             Care at Home  ...              500213
41  Lowell General Hospital  Lowell General Hospital  ...                8371
42             Care at Home             Care at Home  ...              502646
43  Lowell General Hospital  Lowell General Hospital  ...                9019
44             Care at Home             Care at Home  ...              507486
45  Lowell General Hospital  Lowell General Hospital  ...               95695
46  Lowell General Hospital  Lowell General Hospital  ...               13706
47  Lowell General Hospital  Lowell General Hospital  ...                5821
48  Lowell General Hospital  Lowell General Hospital  ...               13706
49  Lowell General Hospital  Lowell General Hospital  ...                8392

   manager_employee_name     fte_status is_per_deim  cell_phone work_phone  \
0                    NaN      Full_time         NaN  978xxxxxxx        NaN
1                    NaN      Full_time         NaN  978xxxxxxx        NaN
2                    NaN  Variable_time         NaN  978xxxxxxx        NaN
3                    NaN      Full_time         NaN  978xxxxxxx        NaN
5                    NaN      Full_time         NaN  603xxxxxxx        NaN
6                    NaN      Full_time         NaN  978xxxxxxx        NaN
8                    NaN      Full_time         NaN  978xxxxxxx        NaN
9                    NaN      Full_time         NaN  978xxxxxxx        NaN
10                   NaN      Full_time         NaN  339xxxxxxx        NaN
12                   NaN      Full_time         NaN  508xxxxxxx        NaN
13                   NaN      Full_time         NaN  978xxxxxxx        NaN
15                   NaN      Full_time         NaN  978xxxxxxx        NaN
16                   NaN  Variable_time         NaN  978xxxxxxx        NaN
17                   NaN      Full_time         NaN  603xxxxxxx        NaN
18                   NaN      Full_time         NaN  978xxxxxxx        NaN
19                   NaN      Full_time         NaN  978xxxxxxx        NaN
21                   NaN      Full_time         NaN  978xxxxxxx        NaN
24                   NaN      Full_time         NaN  978xxxxxxx        NaN
26                   NaN      Full_time         NaN  978xxxxxxx        NaN
28                   NaN      Part_time         NaN  978xxxxxxx        NaN
30                   NaN      Part_time         NaN  978xxxxxxx        NaN
35                   NaN      Full_time         NaN  978xxxxxxx        NaN
36                   NaN      Full_time         NaN  978xxxxxxx        NaN
37                   NaN      Full_time         NaN  603xxxxxxx        NaN
38                   NaN      Full_time         NaN  978xxxxxxx        NaN
39                   NaN      Full_time         NaN  978xxxxxxx        NaN
40                   NaN      Part_time         NaN  603xxxxxxx        NaN
41                   NaN      Full_time         NaN  978xxxxxxx        NaN
42                   NaN      Full_time         NaN  978xxxxxxx        NaN
43                   NaN      Full_time         NaN  978xxxxxxx        NaN
44                   NaN      Part_time         NaN  978xxxxxxx        NaN
45                   NaN      Full_time         NaN  978xxxxxxx        NaN
46                   NaN      Full_time         NaN  603xxxxxxx        NaN
47                   NaN      Full_time         NaN  603xxxxxxx        NaN
48                   NaN      Part_time         NaN  978xxxxxxx        NaN
49                   NaN      Full_time         NaN  978xxxxxxx        NaN

   scheduled_weekly_hour  active_status              termination_reason  \
0                     40              1                             NaN
1                     40              1                             NaN
2                     40              1                             NaN
3                     40              0  Terminate_Employee_Involuntary
5                     40              1                             NaN
6                     40              1                             NaN
8                     40              1                             NaN
9                     40              1                             NaN
10                    40              1                             NaN
12                    40              1                             NaN
13                    40              1                             NaN
15                    40              1                             NaN
16                    40              0    Terminate_Employee_Voluntary
17                    40              1                             NaN
18                    40              1                             NaN
19                    40              1                             NaN
21                    40              1                             NaN
24                    40              1                             NaN
26                    40              1                             NaN
28                    40              1                             NaN
30                    40              1                             NaN
35                    40              1                             NaN
36                    40              1                             NaN
37                    40              1                             NaN
38                    40              1                             NaN
39                    40              0  Terminate_Employee_Involuntary
40                    40              1                             NaN
41                    40              1                             NaN
42                    40              1                             NaN
43                    40              1                             NaN
44                    40              1                             NaN
45                    40              1                             NaN
46                    40              1                             NaN
47                    40              1                             NaN
48                    40              0    Terminate_Employee_Voluntary
49                    40              1                             NaN

   clinical_level
0             NaN
1             NaN
2             NaN
3             NaN
5             NaN
6             NaN
8             NaN
9             NaN
10            NaN
12            NaN
13            NaN
15            NaN
16            NaN
17            NaN
18            NaN
19            NaN
21            NaN
24            NaN
26            NaN
28            NaN
30            NaN
35            NaN
36            NaN
37            NaN
38            NaN
39            NaN
40            NaN
41            NaN
42            NaN
43            NaN
44            NaN
45            NaN
46            NaN
47            NaN
48            NaN
49            NaN

[36 rows x 34 columns]

In [ ]:
employee_ids = set(df['client_employee_id'].dropna().unique())

invalid_managers = df[
    df['manager_employee_id'].notna() &
    ~df['manager_employee_id'].isin(employee_ids)
]

print("Invalid managers:", len(invalid_managers))

In [8]:
df['organization_name'].unique()

array(['Lowell General Hospital', 'Care at Home', 'Tufts Medicine'],
      dtype=object)

In [9]:
# Group by employee ID and count the number of unique organizations (or organization names)
emp_org_counts = df.groupby('client_employee_id')['organization_name'].nunique()

# Get the IDs of employees who have more than 1 unique organization
multi_org_emp_ids = emp_org_counts[emp_org_counts > 1].index

# Filter the original dataframe to show only the records of those employees
multi_org_employees = df[df['client_employee_id'].isin(multi_org_emp_ids)].sort_values('client_employee_id')

# Display the result
multi_org_employees[['client_employee_id', 'first_name', 'last_name', 'organization_name']]

Empty DataFrame
Columns: [client_employee_id, first_name, last_name, organization_name]
Index: []

In [10]:
dept_manager_count = df.groupby('department_id')['manager_employee_id'].nunique()

print(dept_manager_count)

department_id
209037        1
209038        1
214401        1
214638        1
217001        1
220001        1
220537        1
227001        1
235540        1
236037        1
236045        1
236082        1
241028        1
241037        2
246037        2
246045        1
247037        2
247045        1
250045        1
60700         1
60900         1
61100         1
63200         1
68250         1
69000         1
69200         1
71200         1
72300         1
72640         1
72800         2
73480         1
73600         1
75000         1
8000-13204    1
8000-13206    1
8000-14678    1
90420         1
98230         1
Name: manager_employee_id, dtype: int64

In [11]:
# Check Employee <-> Organization
emp_multi_org = (df.groupby('client_employee_id')['organization_id'].nunique() > 1).any()
org_multi_emp = (df.groupby('organization_id')['client_employee_id'].nunique() > 1).any()
print(f"Employee <-> Organization Many-to-Many: {emp_multi_org and org_multi_emp}")

# Check Employee <-> Department
emp_multi_dept = (df.groupby('client_employee_id')['department_id'].nunique() > 1).any()
dept_multi_emp = (df.groupby('department_id')['client_employee_id'].nunique() > 1).any()
print(f"Employee <-> Department Many-to-Many: {emp_multi_dept and dept_multi_emp}")

# Check Employee <-> Manager
emp_multi_mgr = (df.groupby('client_employee_id')['manager_employee_id'].nunique() > 1).any()
mgr_multi_emp = (df.groupby('manager_employee_id')['client_employee_id'].nunique() > 1).any()
print(f"Employee <-> Manager Many-to-Many: {emp_multi_mgr and mgr_multi_emp}")

Employee <-> Organization Many-to-Many: False
Employee <-> Department Many-to-Many: False
Employee <-> Manager Many-to-Many: False

In [12]:
def check_relationship(df, entity1_col, entity2_col, entity1_name, entity2_name):
    # Calculate the maximum number of unique entity2 per entity1
    max_e2_per_e1 = df.groupby(entity1_col)[entity2_col].nunique().max()
    # Calculate the maximum number of unique entity1 per entity2
    max_e1_per_e2 = df.groupby(entity2_col)[entity1_col].nunique().max()
    
    print(f"--- {entity1_name} vs {entity2_name} ---")
    print(f"Max {entity2_name}s per {entity1_name}: {max_e2_per_e1}")
    print(f"Max {entity1_name}s per {entity2_name}: {max_e1_per_e2}")
    
    if max_e2_per_e1 > 1 and max_e1_per_e2 > 1:
        print(f"Relationship: Many-to-Many\n")
    elif max_e2_per_e1 == 1 and max_e1_per_e2 > 1:
        print(f"Relationship: One-to-Many (1 {entity2_name} has Many {entity1_name}s)\n")
    elif max_e2_per_e1 > 1 and max_e1_per_e2 == 1:
        print(f"Relationship: One-to-Many (1 {entity1_name} has Many {entity2_name}s)\n")
    elif max_e2_per_e1 == 1 and max_e1_per_e2 == 1:
        print(f"Relationship: One-to-One\n")
    else:
        print("Dataset might be empty or missing data\n")

check_relationship(df, 'client_employee_id', 'organization_id', 'Employee', 'Organization')
check_relationship(df, 'client_employee_id', 'department_id', 'Employee', 'Department')
check_relationship(df, 'client_employee_id', 'manager_employee_id', 'Employee', 'Manager')

--- Employee vs Organization ---
Max Organizations per Employee: 1
Max Employees per Organization: 30
Relationship: One-to-Many (1 Organization has Many Employees)

--- Employee vs Department ---
Max Departments per Employee: 1
Max Employees per Department: 5
Relationship: One-to-Many (1 Department has Many Employees)

--- Employee vs Manager ---
Max Managers per Employee: 1
Max Employees per Manager: 10
Relationship: One-to-Many (1 Manager has Many Employees)

In [16]:
employee_ids = set(df['client_employee_id'].dropna().unique())

invalid_managers = df[
    df['manager_employee_id'].notna() &
    ~df['manager_employee_id'].isin(employee_ids)
]

print("Invalid managers:", len(invalid_managers))

Invalid managers: 36

In [17]:
invalid_manager_ids = df[
    df['manager_employee_id'].notna() &
    ~df['manager_employee_id'].isin(df['client_employee_id'])
]['manager_employee_id'].value_counts()

print(invalid_manager_ids)

manager_employee_id
502646    7
507237    3
13706     3
507486    2
9569      1
92189     1
9181      1
5119      1
3297      1
507537    1
4380      1
500713    1
303007    1
412620    1
5892      1
29686     1
507792    1
510271    1
507516    1
500213    1
8371      1
9019      1
95695     1
5821      1
8392      1
Name: count, dtype: int64

In [18]:
df[df['client_employee_id'].isin(invalid_manager_ids.index)]

Empty DataFrame
Columns: [client_employee_id, first_name, middle_name, last_name, preferred_name, job_code, job_title, job_start_date, organization_id, organization_name, department_id, department_name, dob, hire_date, recent_hire_date, anniversary_date, term_date, years_of_experience, work_email, address, city, state, zip, country, manager_employee_id, manager_employee_name, fte_status, is_per_deim, cell_phone, work_phone, scheduled_weekly_hour, active_status, termination_reason, clinical_level]
Index: []

[0 rows x 34 columns]

In [19]:
df2.head()

,client_employee_id,department_id,department_name,home_department_id,home_department_name,pay_code,punch_in_comment,punch_out_comment,hours_worked,punch_apply_date,punch_in_datetime,punch_out_datetime,scheduled_start_datetime,scheduled_end_datetime
0,100715,NaN,NaN,NaN,NaN,Hourly,[NULL],[NULL],12.5,2025-10-14,2025-10-14 19:00:00.000,2025-10-15 07:30:00.000,NaN,NaN
1,100801,NaN,NaN,NaN,NaN,Hourly,[NULL],[NULL],8.5,2025-10-09,2025-10-09 07:30:00.000,2025-10-09 16:00:00.000,NaN,NaN
2,100801,NaN,NaN,NaN,NaN,Hourly,[NULL],[NULL],8.5,2025-10-10,2025-10-10 07:00:00.000,2025-10-10 15:30:00.000,NaN,NaN
3,100715,NaN,NaN,NaN,NaN,Hourly,[NULL],[NULL],12.5,2025-10-04,2025-10-04 07:00:00.000,2025-10-04 19:30:00.000,NaN,NaN
4,100715,NaN,NaN,NaN,NaN,Hourly,[NULL],[NULL],12.5,2025-10-10,2025-10-10 07:00:00.000,2025-10-10 19:30:00.000,NaN,NaN

In [35]:
dept_max = df2.groupby("department_id")["home_department_id"].nunique().max()
home_max = df2.groupby("home_department_id")["department_id"].nunique().max()

if dept_max == 1 and home_max == 1:
    relation = "One-to-One"
elif dept_max > 1 and home_max == 1:
    relation = "One-to-Many (Department → Home)"
elif dept_max == 1 and home_max > 1:
    relation = "One-to-Many (Home → Department)"
else:
    relation = "Many-to-Many"

print(relation)

Many-to-Many

In [25]:
home_to_dept = (
    df2.groupby('home_department_id')['department_id']
    .nunique()
    .reset_index(name='unique_departments')
)

print(home_to_dept.sort_values(by='unique_departments', ascending=False))

    home_department_id  unique_departments
173          201-10046                  24
174          201-10047                  23
178          201-10051                  19
325          201-12493                  17
155          201-10011                  16
..                 ...                 ...
528         8000-14396                   0
531         8000-14679                   0
532          805-11550                   0
534          805-14381                   0
540          820-13551                   0

[557 rows x 2 columns]

In [27]:
dept_to_home = (
    df2.groupby('department_id')['home_department_id']
    .nunique()
    .reset_index(name='unique_home_departments')
)

print(dept_to_home.sort_values(by='unique_home_departments', ascending=False))

    department_id  unique_home_departments
165     201-10039                       20
154     201-10011                       20
247     201-10178                       19
329     201-14059                       19
164     201-10038                       18
..            ...                      ...
606         98020                        0
607         98100                        0
624         98810                        0
625         98910                        0
626         98931                        0

[627 rows x 2 columns]

In [31]:
mismatch = df2[
    (df2["department_id"] != df2["home_department_id"]) |
    (df2["department_name"] != df2["home_department_name"])
]

print(mismatch)

       client_employee_id department_id          department_name  \
0                  100715           NaN                      NaN
1                  100801           NaN                      NaN
2                  100801           NaN                      NaN
3                  100715           NaN                      NaN
4                  100715           NaN                      NaN
...                   ...           ...                      ...
412566             104813           NaN               Ultrasound
412567             104839           NaN          Case Management
412568             104850     201-13380  HemeOnc Clinic Stoneham
412569             104852           NaN     Breast Health Clinic
412570             104885           NaN    Dept of Public Safety

       home_department_id home_department_name  pay_code punch_in_comment  \
0                     NaN                  NaN    Hourly           [NULL]
1                     NaN                  NaN    Hourly           [NULL]
2                     NaN                  NaN    Hourly           [NULL]
3                     NaN                  NaN    Hourly           [NULL]
4                     NaN                  NaN    Hourly           [NULL]
...                   ...                  ...       ...              ...
412566                NaN                  NaN    SEIU 8           [NULL]
412567                NaN                  NaN  Per Diem      UNSCHEDULED
412568                NaN                  NaN    Hourly           [NULL]
412569                NaN                  NaN    Hourly      UNSCHEDULED
412570                NaN                  NaN    Hourly           [NULL]

       punch_out_comment  hours_worked punch_apply_date  \
0                 [NULL]         12.50       2025-10-14
1                 [NULL]          8.50       2025-10-09
2                 [NULL]          8.50       2025-10-10
3                 [NULL]         12.50       2025-10-04
4                 [NULL]         12.50       2025-10-10
...                  ...           ...              ...
412566            [NULL]          8.47       2025-09-15
412567            [NULL]          4.72       2025-09-15
412568            [NULL]          8.55       2025-09-15
412569            [NULL]          8.38       2025-09-15
412570            [NULL]          8.50       2025-09-15

              punch_in_datetime       punch_out_datetime  \
0       2025-10-14 19:00:00.000  2025-10-15 07:30:00.000
1       2025-10-09 07:30:00.000  2025-10-09 16:00:00.000
2       2025-10-10 07:00:00.000  2025-10-10 15:30:00.000
3       2025-10-04 07:00:00.000  2025-10-04 19:30:00.000
4       2025-10-10 07:00:00.000  2025-10-10 19:30:00.000
...                         ...                      ...
412566  2025-09-15 08:57:00.000  2025-09-15 17:25:00.000
412567  2025-09-15 09:21:00.000  2025-09-15 14:04:00.000
412568  2025-09-15 07:57:00.000  2025-09-15 16:30:00.000
412569  2025-09-15 07:51:00.000  2025-09-15 16:14:00.000
412570  2025-09-15 15:00:00.000  2025-09-15 23:30:00.000

       scheduled_start_datetime   scheduled_end_datetime
0                           NaN                      NaN
1                           NaN                      NaN
2                           NaN                      NaN
3                           NaN                      NaN
4                           NaN                      NaN
...                         ...                      ...
412566  2025-09-15 09:00:00.000  2025-09-15 17:30:00.000
412567                      NaN                      NaN
412568  2025-09-15 08:00:00.000  2025-09-15 16:30:00.000
412569                      NaN                      NaN
412570  2025-09-15 15:00:00.000  2025-09-15 23:30:00.000

[212608 rows x 14 columns]